### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'key')

### ISSUE THREAD

**Issue by inokawa** [inokawa/virtua#597]
### Discussed in https://github.com/inokawa/virtua/discussions/592

<div type='discussions-op-text'>

<sup>Originally posted by **mariia-mitiureva** December 24, 2024</sup>
After updating to 0.39.2 sometimes (quite rare) it crashes with the following error:

<img width="651" alt="image" src="https://github.com/user-attachments/assets/d4c5918c-cd17-429b-be36-71059cee23b1" />

I happens randomly, not sure what can be a trigger. Did it happen to someone else?
</div>

**Comment by inokawa** [comment]
It was reported in
- react@18.3.1 & virtua@0.39.2
- react@19.0.0 & virtua@0.39.0

**Comment by inokawa** [comment]
https://github.com/facebook/react/blob/a160102f3aedae0da2d692e7cf53b28a011b7bc9/packages/react-reconciler/src/ReactFiberRootScheduler.js#L318
https://github.com/facebook/react/blob/a160102f3aedae0da2d692e7cf53b28a011b7bc9/packages/react-reconciler/src/ReactFiberRootScheduler.js#L530

**Comment by RobHannay** [comment]
We have this too. We can't reliably reproduce it I'm afraid.

For us, it mainly seems to happen after leaving the list open for a while, and then coming back to it (refocussing). I could be wrong though

**Comment by aeharding** [comment]
I have a reliable reproduction! For me it happens:

 1. On a `VList` with `keepMounted` used for sticky items (removing `keepMounted` and cannot reproduce)
 2. Scroll down so `keepMounted` is in use
 3. In my app, Voyager, switch accounts (**to account on same instance**) which effectively just reloads with brand new items.

I believe what's happening is I am setting the `keepMounted` but it is slightly stale (value is set in effect), so Virtua sees `keepMounted` index as out-of-bounds and crashes. Essentially, going from list of 40 with `keepMounted={[30]}` to list of 3 items with same `keepMounted` until the next react cycle. So it can be fixed by a sanity check:

```diff
diff --git a/src/features/community/list/ResolvedCommunitiesList.tsx b/src/features/community/list/ResolvedCommunitiesList.tsx
index e5c39b46..18cb02cd 100644
--- a/src/features/community/list/ResolvedCommunitiesList.tsx
+++ b/src/features/community/list/ResolvedCommunitiesList.tsx
@@ -216,7 +216,9 @@ function ResolvedCommunitiesList({
             updateActiveIndex();
           }}
           as={IonList as CustomContainerComponent}
-          keepMounted={activeIndex >= 0 ? [activeIndex] : []}
+          keepMounted={
+            activeIndex >= 0 && activeIndex < items.length ? [activeIndex] : []
+          }
           item={StickyItem}
         >
           {items.map((item, index) => (
```

See here for more: https://github.com/aeharding/voyager/issues/1799#issuecomment-2585342611

Not sure if this is the same issue everyone else is experiencing? If so maybe Virtua could add a sanity check and ignore out of bounds `keepMounted` to avoid crash

**Comment by RobHannay** [comment]
Ah yes! Smoking gun. We're also using `keepMounted` for `sticky` headers

**Comment by mgraczyk** [comment]
FWIW I am seeing this error without using `keepMounted`. Seems to happen whenever one of the items changes size

**Comment by atsui-affinity** [comment]
I'm seeing this error without using `keepMounted` as well. Also, my usecase is when the number of item changes. This problem started happening after version [0.37.0](https://github.com/inokawa/virtua/releases/tag/0.37.0)

**Comment by miapolis** [comment]
0.37.0 [removed the default overscan value of 4](https://github.com/inokawa/virtua/compare/0.36.3...0.37.0#diff-cf50e94b6a65cb69f740c5e6b6c7dcbb3646689ddb0c125444ea55a41c9088d9R170-R176)
```diff
@@ -171,11 +170,11 @@
   {
     children,
     count: renderCountProp,
-    overscan = 4,
-    keepMounted,
+    overscan,
```
Adding `overscan={4}` to `Virtualizer` fixed the issue for me on 0.40.0.

**Comment by atsui-affinity** [comment]
> 0.37.0 [removed the default overscan value of 4](https://github.com/inokawa/virtua/compare/0.36.3...0.37.0#diff-cf50e94b6a65cb69f740c5e6b6c7dcbb3646689ddb0c125444ea55a41c9088d9R170-R176)
> 
> @@ -171,11 +170,11 @@
>    {
>      children,
>      count: renderCountProp,
> -    overscan = 4,
> -    keepMounted,
> +    overscan,
> Adding `overscan={4}` to `Virtualizer` fixed the issue for me on 0.40.0.

Thank you for the information. I attempted to add `overscan={4}`, but unfortunately, the error persists

**Comment by inokawa** [comment]
I fixed a suspicious logic in `0.40.1`. Probably it will fix this issue.
@atsui-affinity Could you test it? Your comment helped debugging a lot. Thanks!

**Comment by atsui-affinity** [comment]
@inokawa - `0.40.1` fixed the issue!

**Comment by inokawa** [comment]
Closing for now. I'll reopen if it reoccurs again.

**Comment by sashamorozov** [comment]
Hello @inokawa 

Unfortunately I still have this bug on version 0.40.3

It triggers when loading a page (nextjs) if `keepMounted` is specified, without this parameter everything is fine, but I really need it for scrolling

![Image](https://github.com/user-attachments/assets/c522aafd-a9e3-457e-93e4-f057440f4f30)

Let me know if there is anything else I can help with!

Thanks

**Comment by inokawa** [comment]
@sashamorozov 
Not sure without seeing your code. Maybe a similar issue to https://github.com/inokawa/virtua/issues/597#issuecomment-2585357016 .

**Comment by sashamorozov** [comment]
@inokawa Thanks, this comment helped me.

I take the index from the list, but apparently the rerenderer changed something in this. I added checks so that the list for searching the index corresponds to what is being rendered and I no longer get this error. It would be great of course if the app didn't crash because of this.
